### ISSUE TITLE
Cirriculum or Curriculum?

### ISSUE THREAD

**Issue by munzirtaha** [mintyfrankie/awesomeCV-Typst-Submodule#2]
Cirriculum appeared in the footer e.g.
#let cvFooterInternational = (
  "": "Cirriculum Vitae",

Isn't it Curriculum?

**Comment by mintyfrankie** [comment]
Hi @munzirtaha thanks for spotting this typo! A quick fix is now patched.

**Comment by munzirtaha** [comment]
There are a still a couple more:
awesomeCV/metadata-demo.typ
30:  "": "Cirriculum Vitae",
31:  "en": "Cirriculum Vitae",
